# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0002_remove_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='book_name',
            field=models.CharField(default='java', max_length=32),
            preserve_default=False,
        ),
    ]
