# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0003_appointment_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delete',
            old_name='librian_id',
            new_name='librarian_id',
        ),
    ]
